summary: Food categories in BPOM processed food division
summary.alt.lang.id_ID: Kategori pangan di BPOM pangan olahan
fields:
  code:
    schema: ['str*', {match: '^[0-9ABC]+$'}]
    pos: 0
    summary: "Code"
    sortable: Yes
    unique: Yes  # currently there are some duplicates
  name:
    schema: "str*"
    pos: 1
    summary: "Name"
    sortable: Yes
    unique: Yes  # currently there are some duplicates
  summary:
    schema: ['str*']
    pos: 2
    summary: "Summary"
    sortable: Yes
    unique: No
  status:
    schema: ['str*']
    pos: 3
    summary: "Status"
    sortable: Yes
    unique: No
pk: code
