summary: Basic characteristics and heavy-metal pollutants in BPOM processed food division
summary.alt.lang.id_ID: Karakteristik dasar dan cemaran logam di BPOM pangan olahan
fields:
  id:
    schema: 'uint*'
    pos: 0
    summary: "ID"
    "summary.alt.lang.id": "ID"
    sortable: Yes
    filterable_regex: Yes
    unique: Yes
  category:
    schema: 'str*'
    pos: 1
    summary: "Category"
    "summary.alt.lang.id": "Kategori"
    sortable: Yes
    filterable_regex: Yes
    unique: Yes
  characteristic:
    schema: 'str*'
    pos: 2
    summary: "Characteristic"
    "summary.alt.lang.id": "Karakteristik"
    sortable: Yes
    filterable_regex: Yes
    unique: Yes
  upper_limit:
    schema: 'str*'
    pos: 3
    summary: "Upper limit"
    "summary.alt.lang.id": "Batas atas"
    sortable: Yes
    filterable_regex: Yes
    unique: Yes
  lower_limit:
    schema: 'str*'
    pos: 4
    summary: "Lower limit"
    "summary.alt.lang.id": "Batas bawah"
    sortable: Yes
    filterable_regex: Yes
    unique: Yes
pk: id
