summary: Ingredients in BPOM processed food division (RBA version)
summary.alt.lang.id_ID: Bahan baku di BPOM pangan olahan (versi RBA)
fields:
  id:
    schema: 'uint*'
    pos: 0
    summary: "ID"
    "summary.alt.lang.id": "ID"
    sortable: Yes
    unique: Yes
  name:
    schema: 'str*'
    pos: 1
    summary: "Name of ingredient"
    "summary.alt.lang.id": "Nama bahan"
    sortable: Yes
    filterable_regex: Yes
    unique: No
  origin:
    schema: "str*"
    pos: 2
    summary: "Country of origin"
    "summary.alt.lang.id": "Negara asal"
    sortable: Yes
    filterable_regex: Yes
    unique: No
  country_of_origin:
    schema: "str*"
    pos: 3
    summary: "Country of origin"
    "summary.alt.lang.id": "Negara asal"
    sortable: Yes
    filterable_regex: Yes
    unique: No
  status:
    schema: "str*"
    pos: 4
    summary: "Status"
    "summary.alt.lang.id": "Status"
    sortable: Yes
    filterable_regex: No
    unique: No
pk: id
