summary: Provinces in Indonesia
summary.alt.lang.id_ID: Provinsi di Indonesia
table_aliases.alt.lang.id_ID: [provinsi_idn]
fields:
  bps_code:
    schema: ['int*', {min: 11, max: 99}]
    pos: 0
    summary: "BPS code"
    summary.alt.lang.id_ID: "Kode BPS"
    sortable: Yes
    unique: Yes
  iso3166_2_code:
    schema: [str*, {match: '^[A-Z]{2}-[A-Z]{2}$'}]
    pos: 1
    summary: "ISO 3166-2 code"
    summary.alt.lang.id_ID: "Kode ISO 3166-2"
    sortable: Yes
    unique: Yes
  id_name:
    schema: [str*, {}]
    pos: 2
    summary: "Name (in Indonesian)"
    summary.alt.lang.id_ID: "Nama (bahasa Indonesia)"
    sortable: Yes
    unique: Yes
  en_name:
    schema: [str*, {}]
    pos: 3
    summary: "Name (in English)"
    summary.alt.lang.id_ID: "Nama (bahasa Inggris)"
    sortable: Yes
    unique: Yes
  id_capital_name:
    schema: [str*]
    pos: 4
    summary: "Capital name (Indonesian)"
    summary.alt.lang.id_ID: "Nama ibukota (bahasa Indonesia)"
    sortable: Yes
    note: "TODO link to locality_id"
  id_island_name:
    schema: [str*, {}]
    pos: 5
    summary: "Island (Indonesian)"
    summary.alt.lang.id_ID: "Pulau"
    note: "TODO link to island_id"
  tags:
    schema: [str*]
    pos: 6
    summary: "Tag"
    summary.alt.lang.id_ID: "Tag"
pk: ind_name
